### ISSUE TITLE
When you click on the named entities, no infobox/popup is appearing

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-frontend#33]
How to reproduce: 
1. open the page http://traces1.saclay.inria.fr/anHALyticsInria/search/index.html
2. search something like the (usual) 'multivariate' 
3. You will get to this page: 
<img width="1276" alt="screen shot 2016-07-11 at 09 52 39" src="https://cloud.githubusercontent.com/assets/15426/16723451/3a1c6ba8-474d-11e6-89ad-8851ea6340f1.png">
4. click on 'estimation' or any named entities... nothing will happens. 

The infobox seems hidden in the panel popping out when you click on Abstract/Keywords...

**Comment by Aazhar** [comment]
@lfoppiano @kermitt2 actually this is problematic, I've tried 3 ways for displaying those entities and all of them are not appreciated ): 
1-the one reported here.
2-using popups, it hides the data.
3-instead of putting the infobox along with abstract panel I've tried to update the widths of the record when an entity is hovered, but this alteration might make the user dizzy.

I'm for the second one!

**Comment by Aazhar** [comment]
I forgot to mention that IES guys want to be able to filter results when clicking on the entity..

**Comment by Aazhar** [comment]
the 4th alternative that I've tried is to expand the record everytime we click on an entity from the title ?

**Comment by kermitt2** [comment]
I think it's all good right now, as of 27.11.2016
